name: F8_module04_K17_db
services:
  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ptai
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5436:5432
  redis:
    image: redis
    ports:
      - 6388:6379
volumes:
  postgres_db: