export const PRODUCT_CONFIG = {
  TITLE: "Sản phẩm",
  SEARCH_PLACEHOLDER: "Tìm sản phẩm...",
  ADD_BTN: "Tạo sản phẩm",
  MODAL: {
    ADD_FORM: {
      TITLE: "Tạo sản phẩm",
      NAME: "Tên",
      PRICE: "Giá",
      SALE_PRICE: "Giá bán",
      SHORT_DESCRIPTION: "Mô tả ngắn",
      DESCRIPTION: "Mô tả",
      CATEGORY: "Danh mục",
      STATUS: "Trạng thái",
      THUMBNAIL: "Thumbnail",
      IMAGES: "Images",
      PLACEHOLDER_NAME: "Tên sản phẩm...",
      ADD_BTN: "Tạo",
      ADD_IMAGE_BTN: "Thêm ảnh",
      LOADING: "Đang xử lý",
      SUCCESS: "Tạo sản phẩm thành công",
      ERROR: "Tạo sản phẩm thất bại",
    },
    UPDATE_FORM: {
      TITLE: "Chỉnh sửa sản phẩm",
      NAME: "Tên",
      STATUS: "Trạng thái",
      PLACEHOLDER_NAME: "Treo tường",
      ADD_BTN: "Chỉnh sửa",
      LOADING: "Đang xử lý",
      SUCCESS: "Chỉnh sửa sản phẩm thành công",
      ERROR: "Chỉnh sửa sản phẩm thất bại",
    },
    DELETE: {
      TITLE: "Xóa sản phẩm",
      DESC: "Sản phẩm đã xóa sẽ không thể khôi phục. Bạn chắc chắn muốn xoá?",
      CANCEL_BTN: "Huỷ",
      DELETE_BTN: "Xóa",
      LOADING: "Đang xử lý",
      SUCCESS: "Xóa sản phẩm thành công",
      ERROR: "Xóa sản phẩm thất bại",
    },
  },
  ZOD_ERRORS: {
    NAME: "Tên sản phẩm không được để trống",
    PRICE: "Giá phải lớn hơn 0",
    DESCRIPTION: "Phần mô tả không được để trống",
    THUMBNAIL: "Thumbnail không được để trống",
    IMAGE: "Image không được để trống",
    CATEGORY_ID: "Hãy chọn danh mục",
  },
  ERRORS: {
    EXIST: "Sản phẩm đã tồn tại",
  },
  TABLE: [
    {
      FIELD: "ID",
      TEXT: "ID",
      CLASS_NAME: "text-left w-[5%]",
    },
    {
      FIELD: "IMAGE",
      TEXT: "Ảnh",
      CLASS_NAME: "text-left w-[15%]",
    },
    {
      FIELD: "NAME",
      TEXT: "Tên sản phẩm",
      CLASS_NAME: "text-left w-[30%]",
    },
    {
      FIELD: "PRICE",
      TEXT: "Giá sản phẩm",
      CLASS_NAME: "text-left w-[15%]",
    },
    {
      FIELD: "CATEGORY",
      TEXT: "Danh mục",
      CLASS_NAME: "text-left w-[10%]",
    },
    {
      FIELD: "STATUS",
      TEXT: "Trạng thái",
      CLASS_NAME: "text-left w-[10%]",
    },
    {
      FIELD: "UPDATED_AT",
      TEXT: "Ngày cập nhật",
      CLASS_NAME: "text-left w-[25%] ",
    },
    {
      FIELD: "ACTION",
      TEXT: "Hành Động",
      CLASS_NAME: "text-center w-[10%]",
    },
  ],
  STATUS: {
    true: "Đang bán",
    false: "Ngừng bán",
  },
};
